### ISSUE TITLE
OSX install instructions with homebrew 2.5.6 fails with an error

### ISSUE THREAD

**Issue by aaronjszy** [synacker/daggy#24]
**Describe the bug**
Installation on osx following the readme.md instructions with latest version of homebrew (2.5.6) fails with an error:
`Error: Calling Non-checksummed download of daggy formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.`

**To Reproduce**
1. Install brew 2.5.6
2. Run  `brew install https://raw.githubusercontent.com/synacker/daggy_homebrew/master/daggy.rb`

**Expected behavior**
The installation osx instructions should work with up to date versions of homebrew.

**Desktop (please complete the following information):**
 - OS: osx 10.15.7

**Comment by synacker** [comment]
@aaronjszy Sorry for delay, I didn't get notification about this issue.
Is this question still relevant?

**Comment by le0park** [comment]
I solved the problem with this solution.
```
curl -O https://raw.githubusercontent.com/synacker/daggy_homebrew/master/daggy.rb
brew install -s daggy.rb
```

**Comment by hitbear518** [comment]
Yes, got error:
`brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of daggy formula file from an arbitrary URL is unsupported!  (UsageError)

**Comment by synacker** [comment]
@hitbear518 I fixed MacOS formula, can you try next command again?
````
brew install https://raw.githubusercontent.com/synacker/daggy_homebrew/master/daggy.rb
````

**Comment by hitbear518** [comment]
Hi, tried again.
Still reporting: `brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of daggy formula file from an arbitrary URL is unsupported!  (UsageError)

**Comment by hitbear518** [comment]
This time install succeeded, but when I try to run daggy,
it reportes:
dyld: Library not loaded: @rpath/libDaggyCore.dylib
  Referenced from: /usr/local/bin/daggy
  Reason: image not found
[1]    18541 abort      daggy

**Comment by synacker** [comment]
@hitbear518 very strange behavior. The formula test daggy run as post install step.
You can try this installer specially for MacOS - it will be in next release - https://393-148928130-gh.circle-artifacts.com/0/tmp/macos_artifacts/daggy-macos-2.0.2.55.dmg .
From other side, can you provide me information about you MacOS version and homebrew settings?

**Comment by hitbear518** [comment]
mac os version :11.2.3 (20D91)
I think my homebrew is also latest version.
what do you mean by "homebrew settings"?

**Comment by synacker** [comment]
@hitbear518 I just trying to understand, why I don't have this problem and what is the difference in out environments.

**Comment by synacker** [comment]
@hitbear518 sorry for delay. I got the answer from homebrew discussion - https://github.com/Homebrew/discussions/discussions/1190#discussioncomment-565333.
This way is not supported now.
Can you try this solution:
````
brew tap synacker/daggy https://github.com/synacker/daggy_homebrew.git
brew install synacker/daggy/daggy
````

**Comment by synacker** [comment]
Last release [has dmg installer](https://github.com/synacker/daggy/releases/download/2.1.0/daggy-macos-2.1.0.0.dmg).
