### ISSUE TITLE
Still looks for the conan executable when CONAN_BUILD=OFF

### ISSUE THREAD

**Issue by yurivict** [synacker/daggy#51]
**Describe the bug**
With ```CONAN_BUILD=OFF``` it fails with this error:
```
-- Conan: checking conan executable
CMake Error at cmake/conan_cmake_wrapper.cmake:802 (message):
  Conan executable not found! Please install conan.
Call Stack (most recent call first):
  cmake/conan_cmake_wrapper.cmake:480 (conan_check)
  cmake/conan_cmake_wrapper.cmake:766 (old_conan_cmake_install)
  cmake/conan.cmake:4 (conan_cmake_run)
  CMakeLists.txt:11 (include)
```

Version: 2.1.2
FreeBSD 13,1

**Comment by synacker** [comment]
@yurivict sorry for delay, I didn't recieved any notifications about this issue. You can try the build [script from Fedora repo](https://src.fedoraproject.org/rpms/daggy/blob/rawhide/f/daggy.spec):
````
cmake -DVERSION=2.1.2 src
````
In this case you don't need to set ````CONAN_BUILD=OFF````.

**Comment by synacker** [comment]
[Added to docs](https://docs.daggy.dev/#install-from-source-with-cmake-choose-for-maintainers) build instractions for maintainers.
